### ISSUE TITLE
Some documentation?

### ISSUE THREAD

**Issue by LPX55** [impiix/tradingview-chart#1]
I would love to use this! But I have no idea how it works...

**Comment by impiix** [comment]
Hi hanyoon93, will try to add some over the weekend.

**Comment by LPX55** [comment]
Don't want to rush you, but a simple explanation would be very helpful! I'm very good at figuring things out :)

**Comment by impiix** [comment]
Please check out example/example.php with sample usage, I also added composer.json and config.yml file, everything now should work from scratch and be easily imported into the project
